Merging upstream change based on the current tip of react-native-windows (#33)
git merge 2c8e741f7b1a87242578d8831161ce09824837f0

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -35,15 +35,17 @@ workflows:
             - linux
             - package-apple-runtime
             - windows
+      - test-emscripten
       - test-linux
       - test-e2e:
           requires:
             - npm
+      - test-e2e-intl
 
 # Default settings for Apple jobs (apple-runtime, test-apple-runtime)
 apple_defaults: &apple_defaults
   macos:
-    xcode: "12.2.0"
+    xcode: 12.2.0
   working_directory: ~/hermes
   environment:
     - TERM: dumb
@@ -419,17 +421,22 @@ jobs:
 
   npm:
     docker:
-      - image: ubuntu:rolling
+      - image: cimg/node:lts
     environment:
       - YARN: yarnpkg
       - TERM: dumb
       - DEBIAN_FRONTEND: noninteractive
     steps:
       - run:
+          name: Print versions
+          command: |
+            node --version
+            yarn --version
+      - run:
           name: Install certificates required to attach workspace
           command: |
-            apt-get update
-            apt-get install -y ca-certificates
+            sudo apt-get update
+            sudo apt-get install -y ca-certificates
 
       - attach_workspace:
           at: /tmp/hermes/input
@@ -438,7 +445,6 @@ jobs:
           name: Install dependencies and set up
           command: |
             mkdir -p /tmp/hermes/output
-            apt-get install -y git npm yarnpkg
 
       - checkout
 
@@ -476,6 +482,73 @@ jobs:
           root: /tmp/hermes/output
           paths:
             - .
+
+  # test to build with emscripten, not run
+  test-emscripten:
+    docker:
+      # emcc requires Python 3.7+
+      - image: debian:buster
+    environment:
+      - HERMES_WS_DIR: /tmp/hermes
+      - EMSDK: /tmp/emsdk
+      - TERM: dumb
+      - DEBIAN_FRONTEND: noninteractive
+    steps:
+      - run:
+          name: Install dependencies
+          command: |
+            apt-get update
+            apt-get install -y \
+                sudo git openssh-client cmake ninja-build python \
+                build-essential libreadline-dev libicu-dev zip python3 \
+                curl
+      - run:
+          name: Setup Emscripten
+          command: |
+            set -x
+            EMSDK_VERSION=2.0.9
+            curl -sfLO "https://github.com/emscripten-core/emsdk/archive/$EMSDK_VERSION.tar.gz"
+            tar -xf "$EMSDK_VERSION.tar.gz"
+            mv "emsdk-$EMSDK_VERSION" "$EMSDK"
+            rm "$EMSDK_VERSION.tar.gz"
+            "$EMSDK/emsdk" install latest
+            "$EMSDK/emsdk" activate latest
+      - checkout
+      - run:
+          name: Set up workspace
+          command: |
+            mkdir -p "$HERMES_WS_DIR"
+            ln -sf "$PWD" "$HERMES_WS_DIR/hermes"
+            sudo cp /usr/bin/ninja /usr/bin/ninja.real
+            # See top comment
+            printf '%s\n' '#!/bin/sh' 'ninja.real -j4 "$@" || ninja.real -j1 "$@"' | sudo tee /usr/bin/ninja
+      - run:
+          name: Build Hermes Compiler
+          command: |
+            cd "$HERMES_WS_DIR"
+            hermes/utils/build/configure.py ./build_host_hermesc
+            # Build the Hermes compiler so that the cross compiler build can
+            # access it to build the VM
+            cmake --build ./build_host_hermesc --target hermesc
+      - run:
+          name: Build Hermes with Emscripten
+          command: |
+            set -x
+            cd "$HERMES_WS_DIR"
+            source "$EMSDK/emsdk_env.sh"
+            "$EMSDK"/upstream/emscripten/emcc --version
+
+            cmake ./hermes \
+                -Bembuild \
+                -GNinja \
+                -DCMAKE_BUILD_TYPE=Release  \
+                -DCMAKE_EXE_LINKER_FLAGS="-s NODERAWFS=1 -s WASM=1 -s ALLOW_MEMORY_GROWTH=1 -s LLD_REPORT_UNDEFINED=1" \
+                -DCMAKE_TOOLCHAIN_FILE="$EMSDK/upstream/emscripten/cmake/Modules/Platform/Emscripten.cmake" \
+                -DIMPORT_HERMESC="$PWD/build_host_hermesc/ImportHermesc.cmake"
+            cmake --build ./embuild --target hermes
+            cmake --build ./embuild --target hermesc
+            cmake --build ./embuild --target emhermesc
+            EMHERMESC="$PWD/embuild/bin/emhermesc.js" node ./hermes/tools/emhermesc/test.js
   test-e2e:
     # For now we run E2E tests on MacOS as running an Android emulator on Linux is
     # not supported with Circle CI:
@@ -507,8 +580,10 @@ jobs:
             . "$NVM_DIR/nvm.sh"
             echo 'export NVM_DIR="$HOME/.nvm"' >> $BASH_ENV
             echo '. "$NVM_DIR/nvm.sh"' >> $BASH_ENV
-            nvm install 12
-            nvm use 12
+            nvm install 14
+            nvm use 14
+            # Reinstall the latest version of Yarn.
+            npm install --global yarn
             brew install gnu-sed
             brew install md5sha1sum
             brew tap homebrew/cask
@@ -517,6 +592,11 @@ jobs:
             echo 'export PATH="/usr/local/share/android-sdk/platform-tools:/usr/local/share/android-sdk/tools/bin:$PATH"' >> $BASH_ENV
             # At some point, adb ended up in platform-tools/platform-tools. Work around that.
             echo 'export PATH="/usr/local/share/android-sdk/platform-tools/platform-tools:$PATH"' >> $BASH_ENV
+      - run:
+          name: Print versions
+          command: |
+            node --version
+            yarn --version
       - run:
           name: Install emulator dependencies
           command: (yes | sdkmanager "platform-tools" "platforms;android-26" "extras;intel;Hardware_Accelerated_Execution_Manager" "build-tools;26.0.0" "system-images;android-26;google_apis;x86" "emulator" --verbose) || true
@@ -538,5 +618,78 @@ jobs:
             ./run.sh --hermes-npm-package /tmp/hermes/input/hermes-engine-v*.tgz
           # The react-native setup tool takes AGES "Installing CocoaPods dependencies"
           no_output_timeout: 45m
+      - store_artifacts:
+          path: /tmp/hermes/output/
+
+  test-e2e-intl:
+    # This is mostly based on the last test-e2e job, hence the comments there holds.
+    macos:
+      xcode: "10.0.0"
+    environment:
+      - TERM: dumb
+      # Homebrew currently breaks while updating:
+      # https://discuss.circleci.com/t/brew-install-fails-while-updating/32992
+      - HOMEBREW_NO_AUTO_UPDATE: 1
+      - JVM_OPTS: -Xmx3200m
+      - ANDROID_HOME: /usr/local/share/android-sdk
+      - ANDROID_SDK_HOME: /usr/local/share/android-sdk
+      - ANDROID_SDK_ROOT: /usr/local/share/android-sdk
+      - QEMU_AUDIO_DRV: none
+      - JAVA_HOME: /Library/Java/Home
+      - HERMES_WS_DIR: /tmp/hermes
+    steps:
+      - checkout
+      - attach_workspace:
+          at: /tmp/hermes/input
+      - run:
+          name: Setup dependencies
+          command: |
+            brew tap homebrew/cask
+            brew cask install android-sdk
+            (yes | sdkmanager "platform-tools" "platforms;android-26" --verbose) || true
+            echo 'export PATH="/usr/local/share/android-sdk/platform-tools:/usr/local/share/android-sdk/tools/bin:$PATH"' >>  ~/.bash_profile
+      - run:
+          name: Install emulator dependencies
+          command: (yes | sdkmanager "extras;intel;Hardware_Accelerated_Execution_Manager" "system-images;android-26;google_apis;x86" "emulator" --verbose) || true
+      - run:
+          name: Create emulator definition
+          command: |
+            avdmanager create avd -n Pixel_2_API_26 -k "system-images;android-26;google_apis;x86" -g google_apis -d "Nexus 5"
+      - run:
+          name: Run emulator in background
+          command: /usr/local/share/android-sdk/emulator/emulator @Pixel_2_API_26 -memory 2048 -noaudio
+          background: true
+      - run:
+          name: Set up build dependencies
+          command: |
+            brew install python3
+            (yes | sdkmanager "ndk;21.0.6113669" "cmake;3.10.2.4988404" --verbose) || true
+            echo 'export PATH="/usr/local/share/android-sdk/cmake/3.10.2.4988404/bin:$PATH"' >>  ~/.bash_profile
+      - run:
+          name: Set up workspace
+          command: |
+            mkdir -p "$HERMES_WS_DIR" "$HERMES_WS_DIR/output"
+            ln -sf "$PWD" "$HERMES_WS_DIR/hermes"
+      - run:
+          name: Build Hermes Compiler
+          command: |
+            cd "$HERMES_WS_DIR"
+            hermes/utils/build/configure.py ./build
+            # Build the Hermes compiler so that the cross compiler build can
+            # access it to build the VM
+            cmake --build ./build --target hermesc
+      - run:
+          name: Build Hermes for Android and Run tests
+          command: |
+            # Ensure the emulator is ready.
+            adb wait-for-device shell 'while [[ -z $(getprop sys.boot_completed) ]]; do sleep 1; done; input keyevent 82'
+            export ANDROID_SDK="$ANDROID_HOME"
+            export ANDROID_NDK="$ANDROID_HOME/ndk/21.0.6113669"
+            cd "$HERMES_WS_DIR/hermes/android"
+            # We need to build only x86 for running the tests. This saves a lot of computing resources.
+            echo 'abis=x86' >> gradle.properties
+            adb logcat -c || true
+            ./gradlew :intltest:preparetest262 && ./gradlew :intltest:connectedAndroidTest
+            adb logcat -d > /tmp/hermes/output/adblog.txt
       - store_artifacts:
           path: /tmp/hermes/output/
